- name: Deploy artifact
  hosts: localhost
  become: true  # If you need sudo/root access
  tasks:
    - name: Ensure the deployment directory exists
      file:
        path: /opt/deploy
        state: directory
        mode: '0755'

    - name: Copy the artifact to the deployment directory
      copy:
        src: /var/lib/jenkins/workspace/mvn7/target/HelloMaven-1.0-SNAPSHOT.jar
        dest: /opt/deploy/likitha.jar
